"use client";

import { createContext, useContext, useState } from "react";

type Lang = "ko" | "en";

const translations = {
  // Header
  "nav.services": { ko: "서비스", en: "Services" },
  "nav.about": { ko: "소개", en: "About" },
  "nav.contact": { ko: "문의", en: "Contact" },

  // Hero
  "hero.tag": { ko: "AI 기반 크리에이티브 플랫폼", en: "AI-Powered Creative Platform" },
  "hero.prefix": { ko: "AI로", en: "Create" },
  "hero.suffix": { ko: "만들어보세요", en: "with AI" },
  "hero.desc1": {
    ko: "AI Page에서 다양한 AI 서비스를 하나의 공간에서 경험하세요.",
    en: "Experience a variety of AI services in one place.",
  },
  "hero.desc2": {
    ko: "이미지, 음악, 영상, 글쓰기, 코드까지 — 모든 창작을 AI와 함께.",
    en: "Images, music, video, writing, code — create everything with AI.",
  },
  "hero.cta.primary": { ko: "서비스 둘러보기", en: "Explore Services" },
  "hero.cta.secondary": { ko: "자세히 알아보기", en: "Learn More" },

  // Hero rotating words
  "hero.word.image": { ko: "이미지를", en: "images" },
  "hero.word.music": { ko: "음악을", en: "music" },
  "hero.word.video": { ko: "영상을", en: "videos" },
  "hero.word.code": { ko: "코드를", en: "code" },
  "hero.word.text": { ko: "글을", en: "text" },

  // Service cards
  "service.image.title": { ko: "이미지 생성", en: "Image Generation" },
  "service.image.desc": { ko: "텍스트로 상상을 현실로", en: "Turn imagination into reality" },
  "service.music.title": { ko: "음악 생성", en: "Music Generation" },
  "service.music.desc": { ko: "AI가 만드는 오리지널 사운드", en: "Original sounds created by AI" },
  "service.video.title": { ko: "영상 제작", en: "Video Creation" },
  "service.video.desc": { ko: "아이디어를 영상으로 변환", en: "Transform ideas into videos" },
  "service.text.title": { ko: "글쓰기", en: "Writing" },
  "service.text.desc": { ko: "블로그, 카피, 콘텐츠 작성", en: "Blog, copy & content writing" },
  "service.code.title": { ko: "코드 생성", en: "Code Generation" },
  "service.code.desc": { ko: "자연어로 코드를 작성", en: "Write code with natural language" },
  "service.fortune.title": { ko: "AI 사주", en: "AI Fortune" },
  "service.fortune.desc": { ko: "사주팔자로 보는 나의 운명", en: "Discover your destiny with Four Pillars" },
  "service.calorie.title": { ko: "칼로리 분석", en: "Calorie Analysis" },
  "service.calorie.desc": { ko: "음식 사진으로 칼로리 계산", en: "Calculate calories from food photos" },
  "service.math.title": { ko: "수학 풀이", en: "Math Solver" },
  "service.math.desc": { ko: "수학 문제를 AI가 풀어드립니다", en: "AI solves math problems for you" },

  // Login
  "login.title": { ko: "AI Page에 오신 것을 환영합니다", en: "Welcome to AI Page" },
  "login.desc": { ko: "Google 계정으로 간편하게 시작하세요.", en: "Get started easily with your Google account." },
  "login.google": { ko: "Google로 계속하기", en: "Continue with Google" },
  "login.terms": { ko: "계속 진행하면 서비스 이용약관 및 개인정보처리방침에 동의하는 것으로 간주됩니다.", en: "By continuing, you agree to our Terms of Service and Privacy Policy." },
  "login.back": { ko: "홈으로 돌아가기", en: "Back to Home" },

  // Header
  "header.login": { ko: "로그인", en: "Sign in" },
  "header.logout": { ko: "로그아웃", en: "Sign out" },
  "header.dashboard": { ko: "대시보드", en: "Dashboard" },
  "header.upgrade": { ko: "업그레이드", en: "Upgrade" },
  "header.manage_subscription": { ko: "구독 관리", en: "Manage Subscription" },
  "header.cancel_subscription": { ko: "구독 취소", en: "Cancel Subscription" },
  "header.cancel_confirm": { ko: "정말 구독을 취소하시겠습니까? 현재 결제 기간이 끝나면 Free 플랜으로 변경됩니다.", en: "Are you sure you want to cancel? You will be downgraded to Free at the end of the current billing period." },
  "header.cancel_done": { ko: "구독 취소가 예약되었습니다. 결제 기간 종료 후 Free 플랜으로 전환됩니다.", en: "Cancellation scheduled. You will be downgraded to Free after the current period ends." },

  // Dashboard
  "dashboard.welcome": { ko: "환영합니다", en: "Welcome" },
  "dashboard.subtitle": { ko: "어떤 AI 서비스를 사용해 볼까요?", en: "Which AI service would you like to try?" },
  "dashboard.coming_soon": { ko: "준비 중", en: "Coming Soon" },
  "dashboard.available": { ko: "이용 가능", en: "Available" },
  "dashboard.upgrade": { ko: "요금제 보기", en: "View Plans" },

  // Pricing
  "pricing.title": { ko: "요금제 선택", en: "Choose a Plan" },
  "pricing.credits": { ko: "크레딧", en: "credits" },
  "pricing.select": { ko: "선택하기", en: "Select" },
  "pricing.upgrade": { ko: "업그레이드", en: "Upgrade" },
  "pricing.downgrade": { ko: "다운그레이드", en: "Downgrade" },
  "pricing.monthly": { ko: "/ 월", en: "/ mo" },
  "pricing.current": { ko: "현재 플랜", en: "Current Plan" },
  "pricing.scheduled": { ko: "변경 예정", en: "Scheduled" },
  "pricing.cancelDowngrade": { ko: "다운그레이드 취소", en: "Cancel Downgrade" },
  "pricing.loginRequired": { ko: "로그인 후 이용할 수 있습니다.", en: "Please log in first to subscribe." },
  "pricing.all_services": { ko: "전체 서비스 이용", en: "All services included" },
  "pricing.quality": { ko: "출력 품질", en: "Output Quality" },
  "pricing.quality.pro": { ko: "표준 품질", en: "Standard" },
  "pricing.quality.ultra": { ko: "고품질 (HD/4K)", en: "High Quality (HD/4K)" },
  "pricing.performance": { ko: "AI 성능", en: "AI Performance" },
  "pricing.performance.pro": { ko: "기본", en: "Standard" },
  "pricing.performance.ultra": { ko: "최고 성능", en: "Best Performance" },

  // Profile
  "profile.plan": { ko: "플랜", en: "Plan" },
  "profile.credits": { ko: "크레딧", en: "Credits" },
  "profile.plan.free": { ko: "Free", en: "Free" },
  "profile.plan.pro": { ko: "Pro", en: "Pro" },
  "profile.plan.ultra": { ko: "Ultra", en: "Ultra" },
  "profile.status.active": { ko: "활성", en: "Active" },
  "profile.status.canceled": { ko: "해지 예정", en: "Canceled" },
  "profile.status.inactive": { ko: "비활성", en: "Inactive" },

  // Credits
  "credits.title": { ko: "크레딧 충전", en: "Buy Credits" },
  "credits.buy": { ko: "구매하기", en: "Buy" },

  // Dashboard lock
  "dashboard.locked.title": { ko: "유료 플랜 필요", en: "Paid Plan Required" },
  "dashboard.locked.desc": { ko: "이 서비스를 이용하려면 Pro 이상의 플랜이 필요합니다.", en: "You need a Pro plan or higher to use this service." },
  "dashboard.locked.cta": { ko: "플랜 업그레이드", en: "Upgrade Plan" },
  "dashboard.pro.select": { ko: "이 서비스 선택", en: "Select this service" },
  "dashboard.pro.selected": { ko: "사용 중", en: "Active" },
  "dashboard.pro.limit": { ko: "Ultra 필요", en: "Ultra required" },
  "dashboard.pro.banner": { ko: "Pro 플랜은 1개의 서비스를 이용할 수 있습니다. 서비스를 선택해 주세요.", en: "Pro plan includes 1 service. Please select a service." },
  "dashboard.pro.confirm": { ko: "이 서비스를 선택하시겠습니까? Pro 플랜은 1개의 서비스만 이용할 수 있습니다.", en: "Select this service? Pro plan allows only 1 service." },
  "dashboard.pro.change": { ko: "다른 서비스로 변경하시겠습니까?", en: "Change to this service?" },

  "dashboard.cancel_pending": { ko: "구독 취소가 예약되었습니다. 결제 기간 종료 후 Free 플랜으로 전환됩니다.", en: "Cancellation scheduled. You will be downgraded to Free after the current period ends." },

  // Subscription page
  "subscription.title": { ko: "구독 관리", en: "Subscription Management" },
  "subscription.current_plan": { ko: "현재 플랜", en: "Current Plan" },
  "subscription.status": { ko: "상태", en: "Status" },
  "subscription.next_billing": { ko: "다음 결제일", en: "Next Billing Date" },
  "subscription.monthly_price": { ko: "월 요금", en: "Monthly Price" },
  "subscription.ends_at": { ko: "종료 예정일", en: "Ends At" },
  "subscription.change_plan": { ko: "플랜 변경", en: "Change Plan" },
  "subscription.cancel": { ko: "구독 취소", en: "Cancel Subscription" },
  "subscription.cancel_confirm_title": { ko: "구독을 취소하시겠습니까?", en: "Cancel your subscription?" },
  "subscription.cancel_confirm_desc": { ko: "현재 결제 기간이 끝나면 Free 플랜으로 변경됩니다. 남은 기간 동안은 계속 이용 가능합니다.", en: "You will be downgraded to Free at the end of the current billing period. You can continue using the service until then." },
  "subscription.cancel_confirm_btn": { ko: "네, 취소합니다", en: "Yes, cancel" },
  "subscription.cancel_back": { ko: "돌아가기", en: "Go back" },
  "subscription.canceled_notice": { ko: "구독 취소가 예약되었습니다. {date}까지 이용 가능합니다.", en: "Cancellation scheduled. Service available until {date}." },
  "subscription.uncancel": { ko: "취소 철회", en: "Undo Cancel" },
  "subscription.no_subscription": { ko: "현재 구독 중인 플랜이 없습니다.", en: "You don't have an active subscription." },
  "subscription.subscribe_cta": { ko: "플랜 선택하기", en: "Choose a Plan" },
  "subscription.payment_history": { ko: "결제 내역", en: "Payment History" },
  "subscription.no_payments": { ko: "결제 내역이 없습니다.", en: "No payment history." },
  "subscription.date": { ko: "날짜", en: "Date" },
  "subscription.product": { ko: "상품", en: "Product" },
  "subscription.amount": { ko: "금액", en: "Amount" },
  "subscription.type": { ko: "유형", en: "Type" },
  "subscription.payment_method": { ko: "결제 수단", en: "Payment Method" },
  "subscription.payment_method_desc": { ko: "카드 정보 변경은 Polar 고객 포털에서 관리할 수 있습니다.", en: "Card information can be managed through the Polar customer portal." },
  "subscription.manage_in_polar": { ko: "Polar에서 관리", en: "Manage in Polar" },
  "subscription.reason.purchase": { ko: "구매", en: "Purchase" },
  "subscription.reason.subscription_create": { ko: "구독 시작", en: "Subscription Start" },
  "subscription.reason.subscription_cycle": { ko: "구독 갱신", en: "Renewal" },
  "subscription.reason.subscription_update": { ko: "구독 변경", en: "Plan Change" },
  "subscription.page_info": { ko: "{current} / {total} 페이지", en: "Page {current} of {total}" },
  "subscription.prev": { ko: "이전", en: "Previous" },
  "subscription.next": { ko: "다음", en: "Next" },

  // Services page
  "services.hero.tag": { ko: "AI 서비스", en: "AI Services" },
  "services.hero.title": { ko: "강력한 AI 도구를\n한곳에서 만나보세요", en: "Powerful AI Tools,\nAll in One Place" },
  "services.hero.desc": { ko: "AI Page는 창작에 필요한 모든 AI 서비스를 하나의 플랫폼에서 제공합니다. 각 서비스의 특징을 살펴보고, 나에게 맞는 도구를 찾아보세요.", en: "AI Page brings every AI service you need for creation into one platform. Explore each service and find the right tool for you." },
  "services.cta": { ko: "지금 시작하기", en: "Get Started" },
  "services.features": { ko: "주요 기능", en: "Key Features" },
  "services.usecases": { ko: "활용 사례", en: "Use Cases" },

  "services.image.detail": { ko: "텍스트 프롬프트만으로 고품질 이미지를 생성하세요. 일러스트, 사진, 디지털 아트 등 다양한 스타일을 지원합니다.", en: "Generate high-quality images from text prompts. Supports various styles including illustrations, photos, and digital art." },
  "services.image.feature1": { ko: "다양한 아트 스타일 지원", en: "Multiple art style support" },
  "services.image.feature2": { ko: "고해상도 이미지 출력", en: "High-resolution image output" },
  "services.image.feature3": { ko: "프롬프트 기반 세밀한 조정", en: "Fine-tuning with prompts" },
  "services.image.usecase1": { ko: "소셜 미디어 콘텐츠 제작", en: "Social media content creation" },
  "services.image.usecase2": { ko: "마케팅 배너 및 광고 디자인", en: "Marketing banners & ad design" },
  "services.image.usecase3": { ko: "제품 목업 및 컨셉 아트", en: "Product mockups & concept art" },

  "services.music.detail": { ko: "AI가 작곡한 오리지널 음악을 즉시 만들어보세요. 장르, 분위기, 길이를 지정하면 나만의 음악이 완성됩니다.", en: "Create original AI-composed music instantly. Specify genre, mood, and length to get your own unique soundtrack." },
  "services.music.feature1": { ko: "다양한 장르 및 분위기 선택", en: "Various genres & mood selection" },
  "services.music.feature2": { ko: "상업적 사용 가능한 라이선스", en: "Commercial use license" },
  "services.music.feature3": { ko: "실시간 미리듣기 및 편집", en: "Real-time preview & editing" },
  "services.music.usecase1": { ko: "유튜브 및 팟캐스트 배경음악", en: "YouTube & podcast background music" },
  "services.music.usecase2": { ko: "광고 및 프레젠테이션 사운드", en: "Ad & presentation soundtracks" },
  "services.music.usecase3": { ko: "게임 및 앱 사운드트랙", en: "Game & app soundtracks" },

  "services.video.detail": { ko: "텍스트나 이미지를 입력하면 AI가 영상으로 변환합니다. 짧은 클립부터 스토리 영상까지 다양한 포맷을 지원합니다.", en: "Input text or images and AI transforms them into videos. Supports various formats from short clips to story videos." },
  "services.video.feature1": { ko: "텍스트-투-비디오 변환", en: "Text-to-video conversion" },
  "services.video.feature2": { ko: "자동 자막 및 음성 합성", en: "Auto subtitles & voice synthesis" },
  "services.video.feature3": { ko: "다양한 해상도 및 비율 지원", en: "Multiple resolutions & aspect ratios" },
  "services.video.usecase1": { ko: "SNS 숏폼 콘텐츠 제작", en: "Social media short-form content" },
  "services.video.usecase2": { ko: "제품 소개 및 튜토리얼 영상", en: "Product intro & tutorial videos" },
  "services.video.usecase3": { ko: "교육 및 프레젠테이션 자료", en: "Educational & presentation materials" },

  "services.text.detail": { ko: "블로그 포스트, 마케팅 카피, 보고서 등 다양한 형태의 글을 AI가 작성합니다. 톤과 스타일을 자유롭게 조정하세요.", en: "AI writes various forms of content including blog posts, marketing copy, and reports. Freely adjust tone and style." },
  "services.text.feature1": { ko: "SEO 최적화 글쓰기", en: "SEO-optimized writing" },
  "services.text.feature2": { ko: "다국어 콘텐츠 생성", en: "Multilingual content generation" },
  "services.text.feature3": { ko: "톤 및 스타일 커스터마이징", en: "Tone & style customization" },
  "services.text.usecase1": { ko: "블로그 및 뉴스레터 작성", en: "Blog & newsletter writing" },
  "services.text.usecase2": { ko: "제품 설명 및 광고 카피", en: "Product descriptions & ad copy" },
  "services.text.usecase3": { ko: "이메일 및 비즈니스 문서", en: "Emails & business documents" },

  "services.code.detail": { ko: "자연어로 설명하면 AI가 코드를 작성합니다. 다양한 프로그래밍 언어를 지원하며, 코드 리뷰와 디버깅도 가능합니다.", en: "Describe in natural language and AI writes code. Supports various programming languages with code review and debugging." },
  "services.code.feature1": { ko: "10+ 프로그래밍 언어 지원", en: "10+ programming languages" },
  "services.code.feature2": { ko: "코드 리뷰 및 최적화 제안", en: "Code review & optimization" },
  "services.code.feature3": { ko: "실시간 디버깅 어시스턴트", en: "Real-time debugging assistant" },
  "services.code.usecase1": { ko: "프로토타입 빠른 개발", en: "Rapid prototyping" },
  "services.code.usecase2": { ko: "레거시 코드 리팩토링", en: "Legacy code refactoring" },
  "services.code.usecase3": { ko: "API 개발 및 테스트 코드 생성", en: "API development & test generation" },

  "services.fortune.detail": { ko: "생년월일시를 입력하면 AI가 사주팔자를 분석하여 성격, 적성, 운세를 알려드립니다. 동양 철학과 AI 기술의 만남.", en: "Enter your birth date and time for AI-powered Four Pillars analysis. Discover your personality, aptitude, and fortune through Eastern philosophy meets AI." },
  "services.fortune.feature1": { ko: "사주팔자 자동 분석", en: "Automatic Four Pillars analysis" },
  "services.fortune.feature2": { ko: "성격 및 적성 진단", en: "Personality & aptitude diagnosis" },
  "services.fortune.feature3": { ko: "월별/연별 운세 제공", en: "Monthly & yearly fortune" },
  "services.fortune.usecase1": { ko: "나의 성격과 적성 파악", en: "Understanding personality & aptitude" },
  "services.fortune.usecase2": { ko: "진로 및 직업 상담", en: "Career & job consultation" },
  "services.fortune.usecase3": { ko: "궁합 및 인간관계 분석", en: "Compatibility & relationship analysis" },

  "services.calorie.detail": { ko: "음식 사진을 업로드하면 AI가 음식을 인식하고 칼로리, 영양소를 자동으로 분석합니다. 다이어트와 건강 관리에 활용하세요.", en: "Upload a food photo and AI will recognize the food and automatically analyze calories and nutrients. Use it for diet and health management." },
  "services.calorie.feature1": { ko: "음식 사진 자동 인식", en: "Automatic food photo recognition" },
  "services.calorie.feature2": { ko: "칼로리 및 영양소 분석", en: "Calorie & nutrient analysis" },
  "services.calorie.feature3": { ko: "식단 기록 및 관리", en: "Diet tracking & management" },
  "services.calorie.usecase1": { ko: "다이어트 식단 관리", en: "Diet meal management" },
  "services.calorie.usecase2": { ko: "운동 전후 영양 체크", en: "Pre/post workout nutrition check" },
  "services.calorie.usecase3": { ko: "일일 칼로리 섭취량 추적", en: "Daily calorie intake tracking" },

  "services.math.detail": { ko: "수학 문제를 입력하거나 사진을 올리면 AI가 단계별로 풀이 과정을 설명합니다. 초등부터 대학 수학까지 지원합니다.", en: "Enter a math problem or upload a photo — AI explains the solution step by step. Supports elementary to university-level math." },
  "services.math.feature1": { ko: "단계별 풀이 과정 제공", en: "Step-by-step solution process" },
  "services.math.feature2": { ko: "사진 촬영으로 문제 인식", en: "Problem recognition via photo" },
  "services.math.feature3": { ko: "초등~대학 수학 지원", en: "Elementary to university math" },
  "services.math.usecase1": { ko: "수학 숙제 도움", en: "Math homework help" },
  "services.math.usecase2": { ko: "시험 대비 연습 풀이", en: "Exam preparation practice" },
  "services.math.usecase3": { ko: "수학 개념 이해 및 학습", en: "Understanding math concepts" },

  "services.pricing_section.title": { ko: "나에게 맞는 요금제를 선택하세요", en: "Choose the Right Plan for You" },
  "services.pricing_section.desc": { ko: "모든 서비스는 크레딧 기반으로 이용할 수 있습니다.", en: "All services are available on a credit-based system." },
  "services.pricing_section.cta": { ko: "요금제 보기", en: "View Plans" },

  // About page
  "about.hero.tag": { ko: "AI Page 소개", en: "About AI Page" },
  "about.hero.title": { ko: "AI와 함께하는\n새로운 창작의 시대", en: "A New Era of\nCreation with AI" },
  "about.hero.desc": { ko: "AI Page는 누구나 쉽게 AI의 힘을 활용할 수 있도록 만들어진 올인원 크리에이티브 플랫폼입니다.", en: "AI Page is an all-in-one creative platform built so anyone can easily harness the power of AI." },

  "about.mission.tag": { ko: "미션", en: "Our Mission" },
  "about.mission.title": { ko: "창작의 문턱을 낮추다", en: "Lowering the Barrier to Creation" },
  "about.mission.desc": { ko: "우리는 모든 사람이 기술적 장벽 없이 자신의 아이디어를 현실로 만들 수 있어야 한다고 믿습니다. AI Page는 복잡한 AI 도구들을 하나의 직관적인 플랫폼으로 통합하여, 누구나 전문가 수준의 결과물을 만들 수 있도록 합니다.", en: "We believe everyone should be able to bring their ideas to life without technical barriers. AI Page integrates complex AI tools into one intuitive platform, enabling anyone to produce professional-quality results." },

  "about.platform.tag": { ko: "플랫폼", en: "Platform" },
  "about.platform.title": { ko: "이렇게 작동합니다", en: "How It Works" },
  "about.platform.desc": { ko: "AI Page는 복잡한 AI 기술을 간단한 3단계로 제공합니다.", en: "AI Page delivers complex AI technology in 3 simple steps." },
  "about.step1.num": { ko: "01", en: "01" },
  "about.step1.title": { ko: "서비스 선택", en: "Choose a Service" },
  "about.step1.desc": { ko: "이미지, 음악, 영상, 글쓰기, 코드, 채팅 중 원하는 AI 서비스를 선택하세요.", en: "Pick from image, music, video, writing, code, or chat AI services." },
  "about.step2.num": { ko: "02", en: "02" },
  "about.step2.title": { ko: "프롬프트 입력", en: "Enter a Prompt" },
  "about.step2.desc": { ko: "원하는 결과물을 자연어로 설명하면, AI가 즉시 이해합니다.", en: "Describe your desired output in natural language — the AI understands instantly." },
  "about.step3.num": { ko: "03", en: "03" },
  "about.step3.title": { ko: "결과물 생성", en: "Generate Results" },
  "about.step3.desc": { ko: "몇 초 안에 전문가 수준의 결과물을 받아보세요. 다운로드하거나 바로 활용하세요.", en: "Receive professional-grade results in seconds. Download or use them right away." },

  "about.values.tag": { ko: "핵심 가치", en: "Core Values" },
  "about.values.title": { ko: "우리가 추구하는 것", en: "What We Stand For" },
  "about.value1.title": { ko: "접근성", en: "Accessibility" },
  "about.value1.desc": { ko: "기술적 배경에 관계없이 누구나 AI 도구를 쉽게 사용할 수 있어야 합니다.", en: "Anyone should be able to use AI tools easily, regardless of technical background." },
  "about.value2.title": { ko: "통합", en: "Integration" },
  "about.value2.desc": { ko: "흩어진 도구들을 하나의 플랫폼에서 원활하게 연결합니다.", en: "Seamlessly connecting scattered tools in one unified platform." },
  "about.value3.title": { ko: "품질", en: "Quality" },
  "about.value3.desc": { ko: "최신 AI 모델을 활용하여 항상 최고 수준의 결과물을 제공합니다.", en: "Delivering top-tier results powered by the latest AI models." },
  "about.value4.title": { ko: "신뢰", en: "Trust" },
  "about.value4.desc": { ko: "투명한 가격 정책과 안전한 데이터 관리로 신뢰를 쌓아갑니다.", en: "Building trust through transparent pricing and secure data management." },

  "about.stats.services": { ko: "AI 서비스", en: "AI Services" },
  "about.stats.uptime": { ko: "가동률", en: "Uptime" },
  "about.stats.support": { ko: "지원", en: "Support" },
  "about.stats.support_value": { ko: "24/7", en: "24/7" },
  "about.stats.plans": { ko: "구독 플랜", en: "Plans" },

  "about.story.tag": { ko: "스토리", en: "Our Story" },
  "about.story.title": { ko: "왜 AI Page를 만들었나요?", en: "Why Did We Build AI Page?" },
  "about.story.p1": { ko: "AI 기술이 빠르게 발전하면서, 수많은 AI 도구들이 등장했습니다. 하지만 각각의 도구를 따로 배우고, 따로 결제하고, 따로 관리해야 하는 불편함이 있었습니다.", en: "As AI technology rapidly advanced, countless AI tools emerged. But the inconvenience of learning, paying for, and managing each tool separately became apparent." },
  "about.story.p2": { ko: "AI Page는 이 문제를 해결하기 위해 탄생했습니다. 이미지, 음악, 영상, 글쓰기, 코드, 채팅까지 — 모든 AI 서비스를 하나의 구독으로, 하나의 인터페이스에서 제공합니다.", en: "AI Page was born to solve this problem. Image, music, video, writing, code, chat — all AI services in one subscription, one interface." },
  "about.story.p3": { ko: "우리의 목표는 간단합니다: AI를 더 쉽고, 더 접근 가능하게 만드는 것. 그래서 모든 사람이 자신만의 창작물을 만들 수 있도록 돕는 것입니다.", en: "Our goal is simple: make AI easier and more accessible. So everyone can create their own masterpieces." },

  "about.cta.title": { ko: "AI와 함께 창작을 시작하세요", en: "Start Creating with AI" },
  "about.cta.desc": { ko: "지금 바로 AI Page에 가입하고, 6가지 AI 서비스를 경험해 보세요.", en: "Sign up for AI Page now and experience 6 AI services." },
  "about.cta.primary": { ko: "무료로 시작하기", en: "Start for Free" },
  "about.cta.secondary": { ko: "서비스 살펴보기", en: "Explore Services" },

  // Footer
  "footer.rights": { ko: "All rights reserved.", en: "All rights reserved." },
  "footer.services": { ko: "서비스", en: "Services" },
  "footer.company": { ko: "회사", en: "Company" },
  "footer.company.about": { ko: "소개", en: "About" },
  "footer.company.services": { ko: "서비스 목록", en: "Service List" },
  "footer.support": { ko: "지원", en: "Support" },
  "footer.support.pricing": { ko: "요금제", en: "Pricing" },
  "footer.support.subscription": { ko: "구독 관리", en: "Subscription" },
  "footer.legal": { ko: "법률", en: "Legal" },
  "footer.legal.terms": { ko: "이용약관", en: "Terms of Service" },
  "footer.legal.privacy": { ko: "개인정보처리방침", en: "Privacy Policy" },

  // Music Generation page
  "music.back": { ko: "대시보드로 돌아가기", en: "Back to Dashboard" },
  "music.title": { ko: "AI 음악 생성", en: "AI Music Generation" },
  "music.subtitle": { ko: "프롬프트와 가사를 입력하면 AI가 음악을 만들어 드립니다", en: "Enter a prompt and lyrics — AI will create music for you" },
  "music.credit_cost": { ko: "생성 비용", en: "Generation cost" },
  "music.credits_remaining": { ko: "보유 크레딧", en: "Credits remaining" },
  "music.presets": { ko: "장르 프리셋", en: "Genre Presets" },
  "music.genre.pop": { ko: "팝", en: "Pop" },
  "music.genre.rock": { ko: "록", en: "Rock" },
  "music.genre.jazz": { ko: "재즈", en: "Jazz" },
  "music.genre.classical": { ko: "클래식", en: "Classical" },
  "music.genre.electronic": { ko: "일렉트로닉", en: "Electronic" },
  "music.genre.hiphop": { ko: "힙합", en: "Hip-Hop" },
  "music.genre.folk": { ko: "포크", en: "Folk" },
  "music.genre.rnb": { ko: "R&B", en: "R&B" },
  "music.preset.pop": { ko: "밝고 경쾌한 팝, 캐치한 멜로디, 신시사이저, 드럼 비트, 중간 템포, 여성 보컬", en: "Bright upbeat pop, catchy melody, synthesizers, drum beat, mid-tempo, female vocals" },
  "music.preset.rock": { ko: "에너지 넘치는 록, 일렉트릭 기타 리프, 강한 드럼, 베이스, 빠른 템포, 남성 보컬", en: "Energetic rock, electric guitar riffs, strong drums, bass, fast tempo, male vocals" },
  "music.preset.jazz": { ko: "부드러운 재즈, 피아노 트리오, 색소폰 솔로, 더블베이스, 브러시 드럼, 느긋한 템포", en: "Smooth jazz, piano trio, saxophone solo, double bass, brush drums, relaxed tempo" },
  "music.preset.classical": { ko: "우아한 클래식, 현악 오케스트라, 피아노, 서정적인 멜로디, 느린 템포", en: "Elegant classical, string orchestra, piano, lyrical melody, slow tempo" },
  "music.preset.electronic": { ko: "일렉트로닉 댄스 뮤직, 신시사이저, 808 베이스, 하이햇, 빌드업과 드롭, 빠른 템포", en: "Electronic dance music, synthesizer, 808 bass, hi-hats, build-up and drop, fast tempo" },
  "music.preset.hiphop": { ko: "힙합 비트, 808 드럼, 트랩 하이햇, 무거운 베이스, 오토튠 보컬, 중간 템포", en: "Hip-hop beat, 808 drums, trap hi-hats, heavy bass, autotune vocals, mid-tempo" },
  "music.preset.folk": { ko: "어쿠스틱 포크, 핑거피킹 기타, 하모니카, 업라이트 베이스, 따뜻한 프로덕션, 느린 템포", en: "Acoustic folk, fingerpicked guitar, harmonica, upright bass, warm production, slow tempo" },
  "music.preset.rnb": { ko: "현대적 R&B, 부드러운 보컬, 몽환적 신시사이저, 그루비한 베이스, 중간 템포", en: "Modern R&B, smooth vocals, dreamy synthesizers, groovy bass, mid-tempo" },
  "music.prompt_label": { ko: "프롬프트", en: "Prompt" },
  "music.prompt_placeholder": { ko: "원하는 음악 스타일을 설명하세요. (예: 밝고 경쾌한 팝, 어쿠스틱 기타, 중간 템포, 여성 보컬)", en: "Describe the music style you want. (e.g., Bright upbeat pop, acoustic guitar, mid-tempo, female vocals)" },
  "music.lyrics_label": { ko: "가사", en: "Lyrics" },
  "music.lyrics_placeholder": { ko: "[Verse]\n여기에 가사를 입력하세요...\n\n[Chorus]\n후렴구 가사...", en: "[Verse]\nEnter your lyrics here...\n\n[Chorus]\nChorus lyrics..." },
  "music.optional": { ko: "선택사항", en: "optional" },
  "music.generate": { ko: "음악 생성하기", en: "Generate Music" },
  "music.generating": { ko: "생성 중...", en: "Generating..." },
  "music.generating_desc": { ko: "AI가 음악을 만들고 있습니다", en: "AI is composing your music" },
  "music.generating_time": { ko: "약 1~3분 정도 소요됩니다", en: "This may take about 1-3 minutes" },
  "music.result_title": { ko: "생성 완료!", en: "Generation Complete!" },
  "music.result_desc": { ko: "AI가 만든 음악을 들어보세요", en: "Listen to your AI-generated music" },
  "music.download": { ko: "다운로드", en: "Download" },
  "music.error.no_credits": { ko: "크레딧이 부족합니다. 크레딧을 충전해 주세요.", en: "Not enough credits. Please purchase more credits." },
  "music.error.plan_required": { ko: "유료 플랜이 필요합니다. Pro 이상의 플랜으로 업그레이드해 주세요.", en: "A paid plan is required. Please upgrade to Pro or higher." },
  "music.error.generic": { ko: "음악 생성에 실패했습니다. 잠시 후 다시 시도해 주세요.", en: "Music generation failed. Please try again later." },

  // Music List
  "music.list.title": { ko: "내 음악", en: "My Music" },
  "music.list.empty": { ko: "아직 생성한 음악이 없습니다", en: "No music generated yet" },
  "music.list.empty_desc": { ko: "오른쪽에서 음악을 생성해 보세요", en: "Generate music using the form" },
  "music.list.delete": { ko: "삭제", en: "Delete" },
  "music.list.delete_confirm": { ko: "이 음악을 삭제하시겠습니까?", en: "Delete this music?" },
  "music.list.now_playing": { ko: "재생 중", en: "Now Playing" },

  // Music Player
  "music.player.now_playing": { ko: "재생 중", en: "Now Playing" },

  // Image Generation page
  "image.back": { ko: "대시보드로 돌아가기", en: "Back to Dashboard" },
  "image.title": { ko: "AI 이미지 생성", en: "AI Image Generation" },
  "image.subtitle": { ko: "프롬프트를 입력하면 AI가 이미지를 만들어 드립니다", en: "Enter a prompt — AI will create an image for you" },
  "image.credit_cost": { ko: "생성 비용", en: "Generation cost" },
  "image.credits_remaining": { ko: "보유 크레딧", en: "Credits remaining" },
  "image.presets": { ko: "스타일 프리셋", en: "Style Presets" },
  "image.style.photorealistic": { ko: "사실적", en: "Photorealistic" },
  "image.style.illustration": { ko: "일러스트", en: "Illustration" },
  "image.style.digitalart": { ko: "디지털 아트", en: "Digital Art" },
  "image.style.watercolor": { ko: "수채화", en: "Watercolor" },
  "image.style.oilpainting": { ko: "유화", en: "Oil Painting" },
  "image.style.anime": { ko: "애니메이션", en: "Anime" },
  "image.style.pixelart": { ko: "픽셀 아트", en: "Pixel Art" },
  "image.style.render3d": { ko: "3D 렌더", en: "3D Render" },
  "image.preset.photorealistic": { ko: "사실적인 고품질 사진, 자연스러운 조명, 선명한 디테일, DSLR 카메라 품질", en: "Photorealistic high-quality photo, natural lighting, sharp details, DSLR camera quality" },
  "image.preset.illustration": { ko: "세련된 일러스트레이션, 깔끔한 라인, 플랫 디자인, 생동감 있는 색상", en: "Refined illustration, clean lines, flat design, vibrant colors" },
  "image.preset.digitalart": { ko: "디지털 아트, 선명한 색상, 현대적 스타일, 세밀한 디테일", en: "Digital art, vivid colors, modern style, intricate details" },
  "image.preset.watercolor": { ko: "수채화 스타일, 부드러운 색감, 번지는 효과, 예술적 질감", en: "Watercolor style, soft tones, bleeding effect, artistic texture" },
  "image.preset.oilpainting": { ko: "유화 스타일, 두꺼운 붓 터치, 풍부한 질감, 고전적 느낌", en: "Oil painting style, thick brush strokes, rich texture, classical feel" },
  "image.preset.anime": { ko: "애니메이션 스타일, 큰 눈, 선명한 윤곽선, 일본 만화 느낌", en: "Anime style, large eyes, sharp outlines, Japanese manga aesthetic" },
  "image.preset.pixelart": { ko: "픽셀 아트, 레트로 8비트 게임 스타일, 제한된 색상 팔레트", en: "Pixel art, retro 8-bit game style, limited color palette" },
  "image.preset.render3d": { ko: "3D 렌더링, 부드러운 표면, 사실적 조명, 시네마틱 구도", en: "3D rendering, smooth surfaces, realistic lighting, cinematic composition" },
  "image.aspect_ratio": { ko: "비율", en: "Aspect Ratio" },
  "image.prompt_label": { ko: "프롬프트", en: "Prompt" },
  "image.prompt_placeholder": { ko: "원하는 이미지를 설명하세요. (예: 석양이 지는 해변의 고양이, 사실적인 스타일)", en: "Describe the image you want. (e.g., A cat on a beach at sunset, photorealistic style)" },
  "image.generate": { ko: "이미지 생성하기", en: "Generate Image" },
  "image.generating": { ko: "생성 중...", en: "Generating..." },
  "image.generating_desc": { ko: "AI가 이미지를 만들고 있습니다", en: "AI is creating your image" },
  "image.generating_time": { ko: "약 30초~1분 정도 소요됩니다", en: "This may take about 30s-1 minute" },
  "image.result_title": { ko: "생성 완료!", en: "Generation Complete!" },
  "image.download": { ko: "다운로드", en: "Download" },
  "image.error.no_credits": { ko: "크레딧이 부족합니다. 크레딧을 충전해 주세요.", en: "Not enough credits. Please purchase more credits." },
  "image.error.plan_required": { ko: "유료 플랜이 필요합니다. Pro 이상의 플랜으로 업그레이드해 주세요.", en: "A paid plan is required. Please upgrade to Pro or higher." },
  "image.error.generic": { ko: "이미지 생성에 실패했습니다. 잠시 후 다시 시도해 주세요.", en: "Image generation failed. Please try again later." },

  // Image List
  "image.list.title": { ko: "내 이미지", en: "My Images" },
  "image.list.empty": { ko: "아직 생성한 이미지가 없습니다", en: "No images generated yet" },
  "image.list.empty_desc": { ko: "오른쪽에서 이미지를 생성해 보세요", en: "Generate images using the form" },
  "image.list.delete_confirm": { ko: "이 이미지를 삭제하시겠습니까?", en: "Delete this image?" },

  // Fortune Generation page
  "fortune.back": { ko: "대시보드로 돌아가기", en: "Back to Dashboard" },
  "fortune.title": { ko: "AI 사주 분석", en: "AI Fortune Analysis" },
  "fortune.subtitle": { ko: "생년월일과 시간을 입력하면 AI가 사주팔자를 분석해 드립니다", en: "Enter your birth date and time — AI will analyze your Four Pillars" },
  "fortune.credit_cost": { ko: "분석 비용", en: "Analysis cost" },
  "fortune.credits_remaining": { ko: "보유 크레딧", en: "Credits remaining" },
  "fortune.birth_date": { ko: "생년월일", en: "Birth Date" },
  "fortune.birth_date_placeholder": { ko: "예: 1990-05-15", en: "e.g. 1990-05-15" },
  "fortune.calendar_type": { ko: "달력 유형", en: "Calendar Type" },
  "fortune.solar": { ko: "양력", en: "Solar" },
  "fortune.lunar": { ko: "음력", en: "Lunar" },
  "fortune.leap_month": { ko: "윤달", en: "Leap Month" },
  "fortune.birth_time": { ko: "태어난 시간", en: "Birth Time" },
  "fortune.birth_time_placeholder": { ko: "예: 14:30", en: "e.g. 14:30" },
  "fortune.time_unknown": { ko: "시간 모름", en: "Time Unknown" },
  "fortune.gender": { ko: "성별", en: "Gender" },
  "fortune.male": { ko: "남성", en: "Male" },
  "fortune.female": { ko: "여성", en: "Female" },
  "fortune.generate": { ko: "사주 분석하기", en: "Analyze Fortune" },
  "fortune.generating": { ko: "분석 중...", en: "Analyzing..." },
  "fortune.generating_desc": { ko: "AI가 사주팔자를 분석하고 있습니다", en: "AI is analyzing your Four Pillars" },
  "fortune.generating_time": { ko: "약 30초~1분 정도 소요됩니다", en: "This may take about 30s-1 minute" },
  "fortune.result_title": { ko: "분석 완료!", en: "Analysis Complete!" },
  "fortune.copy": { ko: "복사", en: "Copy" },
  "fortune.copied": { ko: "복사됨!", en: "Copied!" },
  "fortune.download": { ko: "다운로드", en: "Download" },
  "fortune.error.no_credits": { ko: "크레딧이 부족합니다. 크레딧을 충전해 주세요.", en: "Not enough credits. Please purchase more credits." },
  "fortune.error.plan_required": { ko: "유료 플랜이 필요합니다. Pro 이상의 플랜으로 업그레이드해 주세요.", en: "A paid plan is required. Please upgrade to Pro or higher." },
  "fortune.error.generic": { ko: "사주 분석에 실패했습니다. 잠시 후 다시 시도해 주세요.", en: "Fortune analysis failed. Please try again later." },
  "fortune.error.birth_date_required": { ko: "생년월일을 입력해 주세요.", en: "Please enter your birth date." },

  // Fortune List
  "fortune.list.title": { ko: "내 분석 기록", en: "My Analyses" },
  "fortune.list.empty": { ko: "아직 분석 기록이 없습니다", en: "No analyses yet" },
  "fortune.list.empty_desc": { ko: "오른쪽에서 사주를 분석해 보세요", en: "Analyze your fortune using the form" },
  "fortune.list.delete_confirm": { ko: "이 분석 기록을 삭제하시겠습니까?", en: "Delete this analysis?" },

  // Code Generation page
  "code.back": { ko: "대시보드로 돌아가기", en: "Back to Dashboard" },
  "code.title": { ko: "AI 코드 생성", en: "AI Code Generation" },
  "code.subtitle": { ko: "자연어로 설명하면 AI가 코드를 작성해 드립니다", en: "Describe in natural language — AI will write code for you" },
  "code.credit_cost": { ko: "생성 비용", en: "Generation cost" },
  "code.credits_remaining": { ko: "보유 크레딧", en: "Credits remaining" },
  "code.language_label": { ko: "프로그래밍 언어", en: "Programming Language" },
  "code.lang.auto": { ko: "자동 감지", en: "Auto Detect" },
  "code.lang.javascript": { ko: "JavaScript", en: "JavaScript" },
  "code.lang.typescript": { ko: "TypeScript", en: "TypeScript" },
  "code.lang.python": { ko: "Python", en: "Python" },
  "code.lang.java": { ko: "Java", en: "Java" },
  "code.lang.csharp": { ko: "C#", en: "C#" },
  "code.lang.cpp": { ko: "C++", en: "C++" },
  "code.lang.go": { ko: "Go", en: "Go" },
  "code.lang.rust": { ko: "Rust", en: "Rust" },
  "code.lang.swift": { ko: "Swift", en: "Swift" },
  "code.lang.kotlin": { ko: "Kotlin", en: "Kotlin" },
  "code.lang.php": { ko: "PHP", en: "PHP" },
  "code.lang.ruby": { ko: "Ruby", en: "Ruby" },
  "code.lang.html_css": { ko: "HTML/CSS", en: "HTML/CSS" },
  "code.lang.sql": { ko: "SQL", en: "SQL" },
  "code.lang.shell": { ko: "Shell/Bash", en: "Shell/Bash" },
  "code.prompt_label": { ko: "프롬프트", en: "Prompt" },
  "code.prompt_placeholder": { ko: "원하는 코드를 설명하세요. (예: 사용자 인증 API를 Express.js로 만들어줘, JWT 토큰 사용)", en: "Describe the code you want. (e.g., Create a user authentication API with Express.js using JWT tokens)" },
  "code.generate": { ko: "코드 생성하기", en: "Generate Code" },
  "code.generating": { ko: "생성 중...", en: "Generating..." },
  "code.generating_desc": { ko: "AI가 코드를 작성하고 있습니다", en: "AI is writing your code" },
  "code.generating_time": { ko: "약 15초~1분 정도 소요됩니다", en: "This may take about 15s-1 minute" },
  "code.result_title": { ko: "생성 완료!", en: "Generation Complete!" },
  "code.copy": { ko: "복사", en: "Copy" },
  "code.copied": { ko: "복사됨!", en: "Copied!" },
  "code.download": { ko: "다운로드", en: "Download" },
  "code.error.no_credits": { ko: "크레딧이 부족합니다. 크레딧을 충전해 주세요.", en: "Not enough credits. Please purchase more credits." },
  "code.error.plan_required": { ko: "유료 플랜이 필요합니다. Pro 이상의 플랜으로 업그레이드해 주세요.", en: "A paid plan is required. Please upgrade to Pro or higher." },
  "code.error.generic": { ko: "코드 생성에 실패했습니다. 잠시 후 다시 시도해 주세요.", en: "Code generation failed. Please try again later." },

  // Code List
  "code.list.title": { ko: "내 코드", en: "My Code" },
  "code.list.empty": { ko: "아직 생성한 코드가 없습니다", en: "No code generated yet" },
  "code.list.empty_desc": { ko: "오른쪽에서 코드를 생성해 보세요", en: "Generate code using the form" },
  "code.list.delete_confirm": { ko: "이 코드를 삭제하시겠습니까?", en: "Delete this code?" },

  // Writing Generation page
  "writing.back": { ko: "대시보드로 돌아가기", en: "Back to Dashboard" },
  "writing.title": { ko: "AI 글쓰기", en: "AI Writing" },
  "writing.subtitle": { ko: "주제를 입력하면 AI가 고품질의 글을 작성해 드립니다", en: "Enter a topic — AI will write high-quality content for you" },
  "writing.credit_cost": { ko: "생성 비용", en: "Generation cost" },
  "writing.credits_remaining": { ko: "보유 크레딧", en: "Credits remaining" },
  "writing.category_label": { ko: "카테고리", en: "Category" },
  "writing.category.general": { ko: "일반", en: "General" },
  "writing.category.blog": { ko: "블로그", en: "Blog Post" },
  "writing.category.marketing": { ko: "마케팅 카피", en: "Marketing Copy" },
  "writing.category.email": { ko: "이메일", en: "Email" },
  "writing.category.report": { ko: "보고서", en: "Report" },
  "writing.category.story": { ko: "스토리", en: "Story" },
  "writing.tone_label": { ko: "톤/스타일", en: "Tone / Style" },
  "writing.tone.professional": { ko: "전문적", en: "Professional" },
  "writing.tone.casual": { ko: "캐주얼", en: "Casual" },
  "writing.tone.friendly": { ko: "친근한", en: "Friendly" },
  "writing.tone.formal": { ko: "격식체", en: "Formal" },
  "writing.tone.creative": { ko: "창의적", en: "Creative" },
  "writing.tone.persuasive": { ko: "설득력 있는", en: "Persuasive" },
  "writing.prompt_label": { ko: "프롬프트", en: "Prompt" },
  "writing.prompt_placeholder": { ko: "원하는 글의 주제와 내용을 설명하세요. (예: AI 기술의 미래에 대한 블로그 포스트를 작성해줘)", en: "Describe the topic and content you want. (e.g., Write a blog post about the future of AI technology)" },
  "writing.generate": { ko: "글 생성하기", en: "Generate Writing" },
  "writing.generating": { ko: "생성 중...", en: "Generating..." },
  "writing.generating_desc": { ko: "AI가 글을 작성하고 있습니다", en: "AI is writing your content" },
  "writing.generating_time": { ko: "약 15초~1분 정도 소요됩니다", en: "This may take about 15s-1 minute" },
  "writing.result_title": { ko: "생성 완료!", en: "Generation Complete!" },
  "writing.copy": { ko: "복사", en: "Copy" },
  "writing.copied": { ko: "복사됨!", en: "Copied!" },
  "writing.download": { ko: "다운로드", en: "Download" },
  "writing.error.no_credits": { ko: "크레딧이 부족합니다. 크레딧을 충전해 주세요.", en: "Not enough credits. Please purchase more credits." },
  "writing.error.plan_required": { ko: "유료 플랜이 필요합니다. Pro 이상의 플랜으로 업그레이드해 주세요.", en: "A paid plan is required. Please upgrade to Pro or higher." },
  "writing.error.generic": { ko: "글 생성에 실패했습니다. 잠시 후 다시 시도해 주세요.", en: "Writing generation failed. Please try again later." },

  // Writing List
  "writing.list.title": { ko: "내 글", en: "My Writings" },
  "writing.list.empty": { ko: "아직 생성한 글이 없습니다", en: "No writings generated yet" },
  "writing.list.empty_desc": { ko: "오른쪽에서 글을 생성해 보세요", en: "Generate writing using the form" },
  "writing.list.delete_confirm": { ko: "이 글을 삭제하시겠습니까?", en: "Delete this writing?" },

  // Calorie Analysis page
  "calorie.back": { ko: "대시보드로 돌아가기", en: "Back to Dashboard" },
  "calorie.title": { ko: "AI 칼로리 분석", en: "AI Calorie Analysis" },
  "calorie.subtitle": { ko: "음식 사진을 업로드하면 AI가 칼로리와 영양 정보를 분석해 드립니다", en: "Upload a food photo — AI will analyze calories and nutrition for you" },
  "calorie.credit_cost": { ko: "분석 비용", en: "Analysis cost" },
  "calorie.credits_remaining": { ko: "보유 크레딧", en: "Credits remaining" },
  "calorie.upload_label": { ko: "음식 사진", en: "Food Photo" },
  "calorie.upload_drag": { ko: "여기에 사진을 드래그하거나 클릭하여 업로드하세요", en: "Drag a photo here or click to upload" },
  "calorie.upload_hint": { ko: "JPEG, PNG, WebP, GIF 지원 · 최대 10MB", en: "Supports JPEG, PNG, WebP, GIF · Max 10MB" },
  "calorie.upload_button": { ko: "파일 선택", en: "Choose File" },
  "calorie.analyze": { ko: "칼로리 분석하기", en: "Analyze Calories" },
  "calorie.analyzing": { ko: "분석 중...", en: "Analyzing..." },
  "calorie.analyzing_desc": { ko: "AI가 음식을 분석하고 있습니다", en: "AI is analyzing your food" },
  "calorie.analyzing_time": { ko: "약 15초~30초 정도 소요됩니다", en: "This may take about 15-30 seconds" },
  "calorie.result_title": { ko: "분석 완료!", en: "Analysis Complete!" },
  "calorie.copy": { ko: "복사", en: "Copy" },
  "calorie.copied": { ko: "복사됨!", en: "Copied!" },
  "calorie.download": { ko: "다운로드", en: "Download" },
  "calorie.error.no_credits": { ko: "크레딧이 부족합니다. 크레딧을 충전해 주세요.", en: "Not enough credits. Please purchase more credits." },
  "calorie.error.plan_required": { ko: "유료 플랜이 필요합니다. Pro 이상의 플랜으로 업그레이드해 주세요.", en: "A paid plan is required. Please upgrade to Pro or higher." },
  "calorie.error.generic": { ko: "칼로리 분석에 실패했습니다. 잠시 후 다시 시도해 주세요.", en: "Calorie analysis failed. Please try again later." },
  "calorie.error.invalid_file": { ko: "이미지 파일만 업로드할 수 있습니다.", en: "Only image files are allowed." },
  "calorie.error.file_too_large": { ko: "파일 크기가 너무 큽니다. 최대 10MB까지 업로드 가능합니다.", en: "File is too large. Maximum size is 10MB." },

  // Calorie List
  "calorie.list.title": { ko: "내 분석 기록", en: "My Analyses" },
  "calorie.list.empty": { ko: "아직 분석 기록이 없습니다", en: "No analyses yet" },
  "calorie.list.empty_desc": { ko: "오른쪽에서 음식 사진을 분석해 보세요", en: "Analyze a food photo using the form" },
  "calorie.list.delete_confirm": { ko: "이 분석 기록을 삭제하시겠습니까?", en: "Delete this analysis?" },

  // Math Solver page
  "math.back": { ko: "대시보드로 돌아가기", en: "Back to Dashboard" },
  "math.title": { ko: "AI 수학 풀이", en: "AI Math Solver" },
  "math.subtitle": { ko: "수학 문제를 입력하거나 사진을 올리면 AI가 단계별로 풀어 드립니다", en: "Enter a math problem or upload a photo — AI solves it step by step" },
  "math.credit_cost": { ko: "풀이 비용", en: "Solving cost" },
  "math.credits_remaining": { ko: "보유 크레딧", en: "Credits remaining" },
  "math.tab.text": { ko: "텍스트 입력", en: "Text Input" },
  "math.tab.image": { ko: "이미지 업로드", en: "Image Upload" },
  "math.prompt_label": { ko: "수학 문제", en: "Math Problem" },
  "math.prompt_placeholder": { ko: "풀고 싶은 수학 문제를 입력하세요. (예: x² + 5x + 6 = 0 을 풀어주세요)", en: "Enter the math problem you want to solve. (e.g., Solve x² + 5x + 6 = 0)" },
  "math.upload_drag": { ko: "여기에 수학 문제 사진을 드래그하거나 클릭하여 업로드하세요", en: "Drag a math problem photo here or click to upload" },
  "math.upload_hint": { ko: "JPEG, PNG, WebP, GIF 지원 · 최대 10MB", en: "Supports JPEG, PNG, WebP, GIF · Max 10MB" },
  "math.upload_button": { ko: "파일 선택", en: "Choose File" },
  "math.solve": { ko: "풀이하기", en: "Solve" },
  "math.solving": { ko: "풀이 중...", en: "Solving..." },
  "math.solving_desc": { ko: "AI가 문제를 분석하고 풀이하고 있습니다", en: "AI is analyzing and solving the problem" },
  "math.solving_time": { ko: "약 15초~30초 정도 소요됩니다", en: "This may take about 15-30 seconds" },
  "math.result_title": { ko: "풀이 완료!", en: "Solution Complete!" },
  "math.copy": { ko: "복사", en: "Copy" },
  "math.copied": { ko: "복사됨!", en: "Copied!" },
  "math.download": { ko: "다운로드", en: "Download" },
  "math.error.no_credits": { ko: "크레딧이 부족합니다. 크레딧을 충전해 주세요.", en: "Not enough credits. Please purchase more credits." },
  "math.error.plan_required": { ko: "유료 플랜이 필요합니다. Pro 이상의 플랜으로 업그레이드해 주세요.", en: "A paid plan is required. Please upgrade to Pro or higher." },
  "math.error.generic": { ko: "수학 풀이에 실패했습니다. 잠시 후 다시 시도해 주세요.", en: "Math solving failed. Please try again later." },
  "math.error.invalid_file": { ko: "이미지 파일만 업로드할 수 있습니다.", en: "Only image files are allowed." },
  "math.error.file_too_large": { ko: "파일 크기가 너무 큽니다. 최대 10MB까지 업로드 가능합니다.", en: "File is too large. Maximum size is 10MB." },
  "math.error.empty_input": { ko: "문제를 입력하거나 이미지를 업로드해 주세요.", en: "Please enter a problem or upload an image." },

  // Math List
  "math.list.title": { ko: "내 풀이 기록", en: "My Solutions" },
  "math.list.empty": { ko: "아직 풀이 기록이 없습니다", en: "No solutions yet" },
  "math.list.empty_desc": { ko: "오른쪽에서 수학 문제를 풀어 보세요", en: "Solve a math problem using the form" },
  "math.list.delete_confirm": { ko: "이 풀이 기록을 삭제하시겠습니까?", en: "Delete this solution?" },

  // Video Generation page
  "video.back": { ko: "대시보드로 돌아가기", en: "Back to Dashboard" },
  "video.title": { ko: "AI 영상 제작", en: "AI Video Creation" },
  "video.subtitle": { ko: "프롬프트를 입력하면 AI가 영상을 만들어 드립니다", en: "Enter a prompt — AI will create a video for you" },
  "video.credit_cost": { ko: "생성 비용", en: "Generation cost" },
  "video.credits_remaining": { ko: "보유 크레딧", en: "Credits remaining" },
  "video.prompt_label": { ko: "프롬프트", en: "Prompt" },
  "video.prompt_placeholder": { ko: "원하는 영상을 설명하세요. (예: 도쿄 시부야 거리를 걷는 여성, 네온 불빛, 야경)", en: "Describe the video you want. (e.g., A woman walking through a busy Tokyo street at night, neon lights)" },
  "video.generate": { ko: "영상 생성하기", en: "Generate Video" },
  "video.generating": { ko: "생성 중...", en: "Generating..." },
  "video.generating_desc": { ko: "AI가 영상을 만들고 있습니다", en: "AI is creating your video" },
  "video.generating_time": { ko: "약 2~5분 정도 소요됩니다", en: "This may take about 2-5 minutes" },
  "video.result_title": { ko: "생성 완료!", en: "Generation Complete!" },
  "video.download": { ko: "다운로드", en: "Download" },
  "video.error.no_credits": { ko: "크레딧이 부족합니다. 크레딧을 충전해 주세요.", en: "Not enough credits. Please purchase more credits." },
  "video.error.plan_required": { ko: "유료 플랜이 필요합니다. Pro 이상의 플랜으로 업그레이드해 주세요.", en: "A paid plan is required. Please upgrade to Pro or higher." },
  "video.error.generic": { ko: "영상 생성에 실패했습니다. 잠시 후 다시 시도해 주세요.", en: "Video generation failed. Please try again later." },
  "video.audio_label": { ko: "오디오 포함", en: "Include Audio" },
  "video.audio_on": { ko: "오디오 ON", en: "Audio ON" },
  "video.audio_off": { ko: "오디오 OFF", en: "Audio OFF" },
  "video.audio_desc_on": { ko: "영상에 AI 생성 오디오가 포함됩니다", en: "AI-generated audio will be included" },
  "video.audio_desc_off": { ko: "오디오 없이 영상만 생성됩니다 (크레딧 절약)", en: "Video only, no audio (saves credits)" },

  // Video List
  "video.list.title": { ko: "내 영상", en: "My Videos" },
  "video.list.empty": { ko: "아직 생성한 영상이 없습니다", en: "No videos generated yet" },
  "video.list.empty_desc": { ko: "오른쪽에서 영상을 생성해 보세요", en: "Generate videos using the form" },
  "video.list.delete_confirm": { ko: "이 영상을 삭제하시겠습니까?", en: "Delete this video?" },
} as const;

type TranslationKey = keyof typeof translations;

interface LanguageContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ko",
  toggleLang: () => { },
  t: (key) => translations[key].ko,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("ko");

  const toggleLang = () => setLang((l) => (l === "ko" ? "en" : "ko"));

  const t = (key: TranslationKey): string => translations[key][lang];

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
